RedPRL/cooltt

src/bin/main.ml
src/lib/Check.ml
src/lib/Driver.ml
src/lib/ElabBasics.ml
src/lib/ElabBasics.mli
src/lib/ElabMonad.ml
src/lib/ElabMonad.mli
src/lib/Elaborator.ml
src/lib/Nbe.ml
src/lib/Nbe.mli
src/lib/NbeMonads.ml
src/lib/NbeMonads.mli
src/lib/Refiner.ml

working on abstracting nbe into custom monads

---

cooltt.opam
src/lib/Checker.ml
src/lib/DomainData.ml
src/lib/ElabBasics.ml
src/lib/Elaborator.ml
src/lib/Nbe.ml
src/lib/Nbe.mli
src/lib/Refiner.ml
src/lib/Refiner.mli
src/lib/Syntax.ml
src/lib/Tactic.ml
src/lib/Tactic.mli
test/com.cooltt
test/elab.cooltt

unifying closure types, removing cleverness

---

src/basis/Bwd.ml
src/basis/Monad.ml
src/basis/Monad.mli
src/basis/PersistentTable.ml
src/basis/Pp.ml
src/lib/ConcreteSyntaxData.ml
src/lib/Domain.ml
src/lib/Elaborator.ml
src/lib/Nbe.ml
src/lib/Refiner.ml
src/lib/Refiner.mli
src/lib/Syntax.ml
src/lib/Syntax.mli
src/lib/grammar.mly
src/lib/lex.mll
test/com.cooltt
test/nat-path.cooltt

Add coe to surface language.

---

src/lib/ConcreteSyntaxData.ml
src/lib/Elaborator.ml
src/lib/Nbe.ml
src/lib/Refiner.ml
src/lib/Refiner.mli
src/lib/grammar.mly
src/lib/lex.mll
test/com.cooltt

Closes #25 (I think -- @jonsterling ?).

Add hcom and com to surface language.

---

src/lib/grammar.mly
src/lib/lex.mll
test/com.cooltt
test/elab.cooltt
test/nat.cooltt
test/pre-path-types.cooltt
test/selfification.cooltt

This is a hack, but _certain_ symbols burn my eyes.

Remove Double Equal Signs.

---

src/lib/grammar.mly
test/com.cooltt

Complete the rectification program.

Close #44.

---

src/lib/lex.mll
test/com.cooltt
test/elab.cooltt
test/nat-path.cooltt
test/nat.cooltt
test/path-types.cooltt
test/pre-path-types.cooltt
test/selfification.cooltt
vim/README.md
vim/ftdetect/cooltt.vim
vim/ftplugin/cooltt.vim
vim/install.sh
vim/syntax/cooltt.vim

- more Unicode syntax
- vim syntax highlighting
- block comments

Miscellaneous syntax improvements

---

src/lib/grammar.mly
test/pre-path-types.cooltt

Grammar hacks

---

src/lib/Cof.ml
src/lib/Cof.mli
src/lib/CofEnv.ml
src/lib/Conversion.ml
src/lib/Quote.ml
src/lib/Refiner.ml
src/lib/Refiner.mli
src/lib/Semantics.ml
src/lib/TermBuilder.ml
src/lib/TermBuilder.mli

These interfaces didn't seem to add much, so I figured we could just remove them.

remove binary meet and join interfaces

---

src/lib/Conversion.ml
src/lib/Domain.ml
src/lib/Domain.mli
src/lib/DomainData.ml
src/lib/ElabError.ml
src/lib/ElabErrorData.ml
src/lib/Elaborator.ml
src/lib/Quote.ml
src/lib/Refiner.ml
src/lib/Refiner.mli
src/lib/Semantics.ml
src/lib/Semantics.mli
src/lib/Syntax.ml
src/lib/SyntaxData.ml
src/lib/TermBuilder.ml

El up to isomorphism

---

src/lib/Grammar.mly
src/lib/Lex.mll
vim/syntax/cooltt.vim

Grammar hacks 3.0

---

src/lib/ConcreteSyntaxData.ml
src/lib/Driver.ml
src/lib/Elaborator.ml
src/lib/Elaborator.mli
src/lib/Grammar.mly
test/com.cooltt
test/nat-path.cooltt

For example:
```
def path (A : type) (x : A) (y : A) : type = {
pathd {_ => A} x y
}
```

Declarations applied to telescopes

---

src/lib/Grammar.mly

It seems simpler to ban these useless recursive type annotations altogether.

Make type annotations non-associative.

---

src/lib/Conversion.ml
src/lib/Domain.ml
src/lib/ElabError.ml
src/lib/ElabErrorData.ml
src/lib/Elaborator.ml
src/lib/Quote.ml
src/lib/Refiner.ml
src/lib/Refiner.mli
src/lib/Semantics.ml
src/lib/Semantics.mli
src/lib/Splice.ml
src/lib/Splice.mli
src/lib/TermBuilder.ml
src/lib/TermBuilder.mli
test/v.cooltt

Refinement and elaboration of V types

---

src/lib/Elaborator.ml
src/lib/Elaborator.mli
src/lib/Refiner.ml
src/lib/Refiner.mli
src/lib/Tactic.ml
src/lib/Tactic.mli

Clean up the API.

---

src/lib/Monads.ml
src/lib/Monads.mli
src/lib/Semantics.ml
src/lib/Splice.ml
src/lib/Splice.mli
src/lib/Syntax.ml
src/lib/SyntaxData.ml

add explicit substitutions to the core language (resolve #135)

---

doc/kan.tex
doc/refs.bib

In light of the fact that some outsiders may be looking at this document soon (due to my upcoming talk), I have made some changes.
- I have replaced the cool pseudonym with the real authors (Angiuli, Cavallo, Favonia, Sterling): we can find other ways to worship St. Facaan.
- I have made some clarificatory changes to the remark on cap/tube.
- I have improved some formatting and notation.
- I have added a few more citations.

Updates to the document

---

doc/kan.tex
src/lib/CofThy.ml
src/lib/Dim.ml
src/lib/TermBuilder.ml

I noticed a couple typos and had something else I wanted to fix since the other day.
By the way, we don't yet have a test case that can detect a problem with the el_in, but I think my change is clearly correctness-preserving.

A few random things I did one night

---

src/lib/CofThy.ml
src/lib/CofThy.mli
src/lib/ElabEnv.ml
src/lib/Monads.ml

Clean up Monads.ml.

---

src/lib/Conversion.ml
src/lib/ElabBasics.ml
src/lib/ElabBasics.mli
src/lib/Elaborator.ml
src/lib/Quote.ml
src/lib/Refiner.ml
src/lib/Semantics.ml
src/lib/Semantics.mli
test/evan.cooltt
test/groupoid-laws.cooltt
test/nat-path.cooltt
vim/syntax/cooltt.vim

Third time's the charm lol
Resolves #139

fixing unfolding again

---

src/lib/Conversion.ml
src/lib/Domain.ml
src/lib/DomainData.ml
src/lib/Quote.ml
src/lib/Refiner.ml
src/lib/Semantics.ml
src/lib/Semantics.mli
src/lib/Splice.ml
src/lib/Splice.mli

The main purpose of this PR is to simplify and make explicit the invariants around `El` and friends. Other changes are also included that make the code a bit better organized. Also bug fixes.

Refactoring the domain

---

src/lib/ConcreteSyntaxData.ml
src/lib/Conversion.ml
src/lib/Domain.ml
src/lib/DomainData.ml
src/lib/Elaborator.ml
src/lib/Grammar.mly
src/lib/Lex.mll
src/lib/Monads.ml
src/lib/Monads.mli
src/lib/Quote.ml
src/lib/Refiner.ml
src/lib/Refiner.mli
src/lib/Semantics.ml
src/lib/Splice.ml
src/lib/Syntax.ml
src/lib/SyntaxData.ml
src/lib/TermBuilder.ml
src/lib/TermBuilder.mli
test/circle.cooltt
test/com.cooltt
test/elab.cooltt
test/evan.cooltt
test/groupoid-laws.cooltt
test/hlevel.cooltt
test/nat-path.cooltt
test/path-types.cooltt
vim/syntax/cooltt.vim

add extension types, remove path types

---

test/hlevel.cooltt

I've tried proving `prop-set` but couldn't figure it out for now :)

hlevel additions

---

src/frontend/Grammar.mly
test/hcom-type.cooltt
test/hlevel.cooltt
test/path-types.cooltt
test/pre-path-types.cooltt
test/v.cooltt

These days the power of genies seems to be wasted.

Grammar hack for projectors

---

test/isos.cooltt

This a partial port of `cool/isos.red`, I've ran into some issues with `void` and `or` proofs so they're not in here.

Isomorphisms

---

src/core/Conversion.ml
src/core/Domain.ml
src/core/DomainData.ml
src/core/Quote.ml
src/core/RefineEnv.ml
src/core/RefineError.ml
src/core/RefineErrorData.ml
src/core/Refiner.ml
src/core/Refiner.mli
src/core/Semantics.ml
src/core/Splice.ml
src/core/Syntax.ml
src/core/SyntaxData.ml
src/core/TermBuilder.ml
src/core/TermBuilder.mli
src/frontend/ConcreteSyntaxData.ml
src/frontend/Elaborator.ml
src/frontend/Grammar.mly
src/frontend/Lex.mll
test/axiom.cooltt
vim/syntax/cooltt.vim

Locked truth wrappers 

---

test/path-types.cooltt

This is the reverse direction of Lemma 3.2.6 in Evan's thesis, but phrased using extension types. Just for fun.

Dependent funext example

---

src/core/Refiner.ml
src/core/Refiner.mli
src/frontend/Elaborator.ml

Resolves #192. I should have reviewed #174 more carefully lol!! 😆

Fix holes and probes

---

src/core/Domain.ml
src/core/Quote.ml
src/core/Refiner.ml
src/core/Refiner.mli
src/core/Semantics.ml
src/core/Syntax.ml
src/cubical/Cof.ml
src/cubical/Cof.mli
src/cubical/CofThy.ml
src/frontend/ConcreteSyntaxData.ml
src/frontend/Elaborator.ml
src/frontend/Grammar.mly
src/frontend/Lex.mll
test/com.cooltt
vim/syntax/cooltt.vim

This reverts commit 8680becd4daf258d52d4a40924d8c9d3fb107030.

⏪ Revert "☯️ Negations (#201)"

---

cooltt.opam
src/core/Ident.ml
src/core/Ident.mli
src/core/Namespace.ml
src/core/Namespace.mli
src/core/RefineEnv.ml
src/core/dune
src/frontend/Grammar.mly

1. Behavioral changes: duplicate names are reported with fully qualified names.
2. Core language changes: allow empty names in the core language.

📖 Use yuujinchou

---

src/cubical/Cof.ml

My Ch'i always got drained when I saw these 16 cases in `meet2` and `join2`. This PR is to replace the code with potentially slower (but empirically equivalent) one that **will not** burn my eyes.

✨ Simplification of mee2 and join2

---

src/frontend/Lex.mll
test/import.cooltt
test/names.cooltt
test/test.expected
vim/syntax/cooltt.vim

```
import /- comment -/ -- more comment
/-
LOL
-/
prelude
```

🔤 Tweaks to the lexer.

---

Makefile
test/dune

Related to #240
Should serve as an example on how to set a test setup, note that in the long term you are going to want incremental test running so at some point it makes sense to split the runner in sub-sections.

[build] Always display test results + timing friendly target

---

src/frontend/ConcreteSyntaxData.ml
src/frontend/Elaborator.ml
src/frontend/Grammar.mly
test/base-types.cooltt
test/circle.cooltt
test/com.cooltt
test/elab.cooltt
test/hlevel.cooltt
test/isos.cooltt
test/nat.cooltt
test/path-types.cooltt
test/prelude.cooltt
test/selfification.cooltt
test/test.expected

_"Why not?"_---asked by a genie.

🧞 Bind multiple variables in a telescope cell.

---

src/core/Syntax.ml
src/core/Syntax.mli
src/core/SyntaxPrecedence.ml
src/core/SyntaxPrecedence.mli
test/test.expected

🧺 Precedence-directed parenthesis insertion

---

.github/workflows/ocaml.yml
.github/workflows/odoc.yml
cooltt.opam

⬆️ New GitHub Actions and the OPAM file

---

src/frontend/Elaborator.ml

Match the planned clean-up in RedPRL/yuujinchou#52

🔖 Match the planned clean-up in Yuujinchou#52

---

Makefile

Finish what's left to be done in PR #291.

🔪 Kill the remaining pinning in Makefile for Yuujinchou

---

test/import.cooltt

Bug discovered during WITS. Credit to @camelid.

📝 correct comments (thanks to @camelid)

---

Dockerfile
src/frontend/dune

Solve the fundamental problem in #308.

🐫 Run opam update in Dockerfile

---

Dockerfile
cooltt.opam
src/bin/main.ml
src/frontend/dune

⚠️ Update `cmdliner` and fix deprecation warnings

---

src/basis/DisjointSet.ml
src/basis/DisjointSet.mli
src/cubical/CofThy.ml
src/cubical/CofThy.mli
src/cubical/Dim.ml
src/cubical/Dim.mli
src/cubical/dune

Compute the meets of two cofibraiton theories.

↗️↖️ API to merge cofibration theories

---

src/frontend/Grammar.mly
test/import.cooltt

The :genie: is out of :diya_lamp: today.

🧞 Make the pattern grammar more complicated purely for fun

---

src/core/RefineMonad.ml
src/core/RefineMonad.mli
src/core/RefineState.ml
src/core/RefineState.mli
src/core/Refiner.ml
src/frontend/ConcreteSyntaxData.ml
src/frontend/Driver.ml
src/frontend/Grammar.mly
test/base-types.cooltt
test/elab.cooltt
test/groupoid-laws.cooltt
test/holes.cooltt
test/isos.cooltt
test/section.cooltt

📌 Support def and !def and close #319

---

src/frontend/ConcreteSyntaxData.ml
src/frontend/Grammar.mly
src/frontend/Load.ml
src/frontend/Load.mli

Close #317. This is not what the original proposal was planning to do, but still a solution to the problem.

🆔 Rename "command" to "REPL command"

---

src/frontend/ConcreteSyntaxData.ml
src/frontend/Driver.ml
src/frontend/Grammar.mly

Close #316. This would automatically improve error reporting.

🗺 Keep location info in decl and repl_command

---

cooltt.opam

We have to wait for the new OPAM repository to be uploaded. The sync would probably take less than one day.

🔙 Versioned dependency on bwd

---

src/core/Monads.ml
src/cubical/CofThy.ml
src/cubical/CofThy.mli

Currently the left inversion seems to be doing useless optimization.

❌ Drop seemingly pointless optimization

---

cooltt.opam
src/basis/Pp.ml

This might lead to a better analysis of the effect of #358.

🚥 Use the new nth_opt

---

src/basis/Pp.ml

@TOTBWF I can't tell if this is any better...

🔻 Use arrays

---

.gitignore

We should probably thoroughly review the .gitignore file, but I got other things to do.

🐫 Update OCaml .gitignore

---

src/core/Dim.ml

🚫 No polymorphic comparison

---

src/core/DomainData.ml

Check if I replaced it with the right module...

Update outdated reference to Cubical in comment

---

emacs/cooltt.el
src/frontend/ConcreteSyntaxData.ml
src/frontend/Driver.ml
src/frontend/Grammar.mly
src/frontend/Lex.mll
vim/syntax/cooltt.vim

This is a little PR that adds a `#debug` directive that toggles the debug mode on and off via `#debug on` and `#debug off`.

🐛 🚫  Add #debug

---

CONTRIBUTORS.md

Hi, @solomon-b, thanks for your contribution. I wonder if you could explicitly approve this PR as a lightweight mechanism to assign the copyright of all your contributions to **The RedPRL Development Team**? See https://github.com/RedPRL/cooltt/blob/main/CONTRIBUTING.md for more explanation.

docs(CONTRIBUTORS): add Solomon Bothwell
