src/basis/Monad.ml, src/basis/Monad.mli, src/lib/ConcreteSyntax.ml, src/lib/ConcreteSyntax.mli, src/lib/Domain.ml, src/lib/Domain.mli, src/lib/Driver.ml, src/lib/ElabBasics.ml, src/lib/ElabEnv.ml, src/lib/ElabEnv.mli, src/lib/ElabState.ml, src/lib/Elaborator.ml, src/lib/Monads.ml, src/lib/Monads.mli, src/lib/Nbe.ml, src/lib/Nbe.mli, src/lib/Refiner.ml, src/lib/Veil.ml, src/lib/Veil.mli, src/lib/grammar.mly, src/lib/lex.mll, test/fib.cooltt
In [this thread](https://github.com/AndrasKovacs/elaboration-zoo/issues/7), @ollef suggested a cool intermediate version of Andras Kovacs's "glued evaluator" style, to prevent unfolding too much during quotation.
=> Binary equate, semi-kovacs-style evaluator

src/lib/Nbe.ml
A bug? Currently if we run 
```
def false-test : (_ : [0=1]) -> nat = {
\_ => []
}
normalize false-test
```
we get
```
Computed normal form of false-test as []
```
but I think it should be
```
Computed normal form of false-test as (lam [_x] [])
```
=> when quoting in pi type, bind var inside lam

src/lib/grammar.mly, test/pre-path-types.cooltt
@Favonia I'm very sorry, but I had to revert this commit. I have made extensive changes to the grammar already in #17 and I realized after I merged your commit that it would be nearly impossible for me to resolve the conflict. 
But source location is a higher priority.
=> Revert "Grammar hacks (#70)"

src/lib/Semantics.ml, src/lib/Syntax.ml, src/lib/SyntaxData.ml
I believe this is sound & complete. It is _only_ possible because we do not allow cofibration variables of higher type: there is no type `A -> cof`.
Resolves #102
=> Universal quantification of cofibrations via quantifier elimination (#102)

src/basis/Monad.ml, src/basis/Monad.mli, src/lib/Domain.ml, src/lib/DomainData.ml, src/lib/Quote.ml, src/lib/Semantics.ml, src/lib/Semantics.mli
This is an alternative to the existing approach to evaluating `coe`; in the existing code, we avoid substitution but must instantiate the binder many times. Maybe that's worse than some very restricted use of substitution! Not sure yet.
In `redtt`, the dimension substitution was a nightmare because we had swapping everywhere, as things were getting drawn underneath binders. That's all been totally eliminated in `cooltt`, using the `TermBuilder`. So, maybe this small bit of substitution is rational.
=> Experimenting with SIMPLE-MINDED explicit substitutions

src/lib/Conversion.ml, src/lib/Elaborator.ml, src/lib/Monads.ml, src/lib/Monads.mli, src/lib/Quote.ml, src/lib/Refiner.ml, src/lib/Semantics.ml, src/lib/Semantics.mli, src/lib/Syntax.ml, test/hlevel.cooltt
This PR fixes a lot of conceptual issues with the way the unfolding is controlled. I believe the current design here makes some sense. Let me describe it.
First of all, there is a notion of _veil_, which is a policy about what identifiers are to be unfolded during quotation; this does *not* affect conversion or evaluation. It is important to remember that definitional equivalence in `cooltt` is closed under unfolding of definitions, so the point of `unfold` is only to control the display. Things get unfolded under the hood when necessary *no matter what*; this would be revisited when we add support for abstraction.
Separately, there is a notion of `whnf` that mediates two things: the reduction of cubically unstable stuff, and the unfolding of definitions, in order to support the …
=> Fix things being unfolded prematurely

src/basis/dune, src/lib/dune
See https://dune.readthedocs.io/en/stable/faq.html#how-to-make-warnings-non-fatal
=> Restore all warnings except unused exceptions.

test/groupoid-laws.cooltt
An example, using cofibration variables to write HoTT-style(-ish) proofs by J without having to adjust by J-on-refl paths all the time.
=> Groupoid laws

src/lib/Quote.ml, src/lib/Semantics.ml
@jonsterling Here is a quick dirty fix for #139, but I do not think this is what we want...? So the issue seems to be that both normalization and goal displaying are using `quote_con`. Not sure what is the most Immortal design here.
How about types? Should we also pass the style in `whnf_tp` (and maybe `quote_tp`) as well.
=> Extremely minor clear-up of Semantics.ml

.github/workflows/ocaml.yml, cooltt.opam
This is to address #157. `List.concat_map` was introduced in 4.10.0.
We should either specify the dependency in the opam file or avoid that function.
=> Fix the OPAM file.

src/bin/main.ml, src/lib/Conversion.ml, src/lib/Driver.ml, src/lib/ElabBasics.ml, src/lib/Elaborator.ml, src/lib/Elaborator.mli, src/lib/Quote.ml, src/lib/Refiner.ml, src/lib/Refiner.mli, src/lib/Semantics.ml, src/lib/Semantics.mli, src/lib/Syntax.ml, src/lib/Tactic.ml, src/lib/Tactic.mli, test/hcom-type.cooltt
Previously chk/bchk were two different kinds of tactics; I have abstracted the representation of tactics, and now can make these into a single type with the section-retraction pair between them mediated dynamically. This makes the code much simpler! It also gets rid of spurious loss-of-information (when a bchk-tactic is spuriously transformed into chk-tac and then into bchk-tac again).
=> Smoother tactic interface; bug fixes

src/basis/Monad.ml, src/basis/Monad.mli, src/lib/Domain.ml, src/lib/Domain.mli, src/lib/ElabBasics.ml, src/lib/ElabBasics.mli, src/lib/ElabError.ml, src/lib/ElabErrorData.ml, src/lib/ElabState.ml, src/lib/ElabState.mli, src/lib/Elaborator.ml, src/lib/Quote.ml, src/lib/Refiner.ml, src/lib/Refiner.mli
Resolves #75 
In the past, the n-ary cofibration splits were elaborated as iterated binary splits; this was ugly and inefficient. I now implemented a general refinement rule for the n-ary split.
=> n-ary split refinement rule

src/core/Domain.ml, src/core/DomainData.ml, src/core/Semantics.ml, src/cubical/Dim.ml, src/cubical/Dim.mli, test/axiom.cooltt
Per our discussion, I tried to switch the "fresh dimension" variables over to use their own constructor `DimSym` in the domain, because these are not treated like global variables (they are not in the top-level signature).
However, I realized that we actually need both! Because it is possible for a user to write something like:
```
axiom foo : II
```
or 
```
def bar : II := 0
```
So let me work that out too.
=> Dimension probe invariants

Makefile, test.sh, test/README.md, test/Test.ml, test/dune, test/test.expected
Prior to this change, we were simply checking to see if `cooltt` could actually load the files in question. This PR adds a simple form of testing where we snapshot the output of `cooltt` on all of our test files, and then compare against this known good snapshot. There is also a handy feature of `dune` that allows us to update the snapshots nicely, which I've added to the makefile under `make snapshot`
Resolves #194
=> Add a Simple Test Suite

src/bin/main.ml, src/frontend/Driver.ml, src/frontend/Driver.mli, test/Test.ml, vim/ftplugin/cooltt.vim
1. Use `--as-file` instead of `--project-root`.
2. The interactive mode will search for the root by default instead of using the current working directory.
3. Architectural changes: no fancy logic in `main.ml` other than option parsing.
PS: I *did not* test the Vim mode or the interactive mode!
=> 🌳 Refactor the search of the project root.

emacs/cooltt.el
This PR fixes a minor highlighting bug in the emacs mode that was causing comments to not be properly highlighted.
=> Fix highlighting of comments in the emacs mode

src/frontend/Driver.ml
The error label `InvalidRoutingTable` was merged into `InvalidRouter`.
=> 📚 Bantorra API updates

src/frontend/DriverMessage.ml
Use the higher-Ch'i error message printing instead of the plain `%s`.
=> ⏎ Hint a break when printing '\n' in error messages.

src/frontend/Grammar.mly, test/names.cooltt, test/test.expected
1. Qualified names can now appear _anywhere._
```
def x.y (z.w : nat) : nat := z.w
print x.y
```
2. `.x.y` is forbidden because `.x .y => ...` is ambiguous.
3. However, name modifiers `. -> p` and `! .` are still allowed until the Wish is reversed. @jonsterling 
4. There are some minor clean-ups just for fun.
=> 🧞 Qualified names everywhere

src/basis/DisjointSet.ml, src/basis/PersistentTable.ml, src/basis/PersistentTable.mli
Path compression is totally useless. Could one of you benchmark the test suite to confirm that this is the case not just on my machines? @jonsterling @TOTBWF My theory is that a data structure even more stupid than this PR would actually work better.
=> 🏃 Stop path compression in union-and-find

src/core/Namespace.ml, src/frontend/Grammar.mly
1. Allow the standalone dot pattern `.`.
2. Slightly better error messages.
=> 🔘 Minor updates to name modifiers

src/core/Quote.ml, test/test.expected
I don't know how to properly deal with `Split` and `TpSplit`.
=> 📛 Preserve some names during normalization.

emacs/cooltt.el
This PR adds some regexes to highlight errors in the `cooltt` compilation output in emacs. This also makes it nice and easy to jump to/between the errors using `next-error`
=> Add compilation-mode regexes for emacs mode

src/bin/main.ml, zsh/README.md, zsh/_cooltt
I removed the code that checks whether the input mode is a prefix of some recognized mode. Seriously, just press <kbd>Tab</kbd>.
=> 🇿 Auto-completion for zsh

src/frontend/Grammar.mly, test/hlevel.cooltt, test/record.cooltt, test/test.expected
This PR updates the grammar for projections to allow for the following syntax:
```
normalize basic.inhabit@bar 1
```
Prior to this change, brackets were required, like so:
```
normalize {basic.inhabit@bar} 1
```
=> 📽️  Update Projection Grammar

src/core/CodeUnit.ml, src/core/CodeUnit.mli, src/core/RefineMonad.ml, src/core/RefineMonad.mli, src/core/RefineState.ml, src/core/RefineState.mli, src/frontend/Driver.ml
This PR removes namespaces from `CodeUnit`s, and pulls it into the `RefinerState` instead. This could be brought out of the core entirely, but would require yet another layer of `StateT`. If a wish is made then this shall be done.
=> 🧶 Detangle Namespaces + Code Units

src/basis/Pp.ml, src/basis/StringUtil.ml, src/basis/StringUtil.mli, test/pp.cooltt, test/test.expected
Out of curiosity, I profiled `cooltt` to see exactly what was preventing us from normalizing really big terms like `loopn 1000`. To my surprise, I found that most of cooltt is super fast, with the exception of the pretty printer environment. In fact, for terms with large amounts of anonymous variables, we were spending like 99% of our time generating fresh names + looking up DeBruijin Indexed names.
To fix this, I've replaced the `string bwd` we used for our env previously with the following data structure:
```ocaml
type t = { names : string CCVector.vector;
bound : int;
used : StringSet.t }
```
This behaves somewhat like a bump-allocator, where we keep track of the current number of bound names, possibly rewriting over previously bound ones in the mutable vector. We also keep track of a …
=> ⚡ Optimize PP.Env

src/core/Refiner.ml, src/core/Refiner.mli, src/core/Semantics.ml, src/core/Semantics.mli, src/core/Syntax.ml, src/core/TermBuilder.ml, src/core/TermBuilder.mli, src/frontend/ConcreteSyntaxData.ml, src/frontend/Elaborator.ml, src/frontend/Grammar.mly, src/frontend/Lex.mll, test/patch.cooltt, test/test.expected
This PR starts work on implementing record patches as described in #266.
This _mostly_ works, but we run into some weird issues with conversion checking. For example, the following _ought_ to typecheck:
```
def testing (A Z : type) (B : A → type)
(p : Z → sig (x : A) (bx : B x))
(z : Z) : sig (x : A) (bx : B x) as x [ x .= {p z} @ x | bx .= {p z} @ bx ] := p z
```
However, we get the following error:
```
Expected sig (x : el {ext el/out A #t {_x => el/out {el/out p z} @ x}})
(bx : el {ext el/out {el/out Z {el/out {el/out B p} @ x}} #t {
_x => el/out {el/out B p} @ bx}})
=
sig (x : el el/out A)
(bx : el el/out {el/out Z z})
```
=> 🪡  Record Patches

emacs/cooltt.el, src/frontend/ConcreteSyntaxData.ml, src/frontend/Driver.ml, src/frontend/Grammar.mly, src/frontend/Lex.mll, test/holes.cooltt, test/test.expected, vim/syntax/cooltt.vim
It is often useful to assert that a given term is *not* supposed to typecheck, especially for our test suite. This PR adds the new `fail` top level declaration, which allows us to do just this!
Here's some examples of how it can be used:
```cooltt
fail nat-fail : nat := type
> holes.cooltt:20.23-20.27 [Info]:
>   fail nat-fail:
>   Head connective mismatch, expected univ but got nat
fail bad-fail : nat := 1
> holes.cooltt:21.0-21.24 [Error]:
>   fail bad-fail:
>   Expected (1 : nat) to fail but it succeded.
```
We log out the cause of the failure under `Info`, as we want to still be able to know that things failed in the way that we expect them to!
=> 🚨 Add `fail` top-level form

cooltt.opam, src/basis/Symbol.ml, src/basis/Symbol.mli, src/basis/dune, src/core/CodeUnit.ml, src/core/CodeUnit.mli, src/core/Serialize.ml, src/core/Serialize.mli, src/core/dune, src/cubical/DimProbe.ml, src/cubical/dune
This PR implements serialization/deserialization of terms and types of both the `Syntax` and `Domain` variety. This is required for a couple of features, most notably some of the coolttviz stuff, as well as interface files. This closes #81.
Currently we serialize into JSON as it is a relatively common format. I know @favonia was interested in some alternative formats, so perhaps those are worth exploring as well.
=> 🌾 Serialization of Terms

src/core/DomainData.ml
One can still have stable codes with `V` and/or `HCom`.
=> 📝 correct comments about (un)stability

cooltt.opam, src/core/Namespace.ml
Currently blocked by ocaml/opam-repository#20859, but the OPAM repository maintainers are very industrious.
=> 🆙 Upgrade Yuujinchou to 2.x

emacs/cooltt.el, src/core/RefineMonad.ml, src/core/RefineMonad.mli, src/core/TermBuilder.mli, src/frontend/ConcreteSyntaxData.ml, src/frontend/Elaborator.ml, src/frontend/Grammar.mly, src/frontend/Lex.mll, src/frontend/Tactics.ml, src/frontend/Tactics.mli, test/equation.cooltt, test/test.expected, vim/syntax/cooltt.vim
This PR adds a small equational reasoning DSL, which makes it somewhat easier to write complicated, multi step proofs.
This closes #305.
Here's a quick example:
```
def equational/trans (a : type) (x y z :  a) (p : path a x y) (q : path a y z) : path a x z :=
equation a begin
x =[ p ]
y =[ q ]
z
end
def equational/refl/nat : path nat 4 4 :=
equation nat begin
4 =[]
4
end
```
It may be possible to have the tactics generate better paths, instead of naively doing `trans` absolutely everywhere. Would love to hear thoughts on this!
=> ↔️ Equational Reasoning DSL

src/core/Log.ml
Before this PR, the error messages without a span could lead to (in my opinion) very ugly output. Such as:
```
Virtual type (dim, cof, etc.) cannot appear in this positioncooltt: encountered one or more errors
```
(no space between "position" and "cooltt"). With this PR, this would be changed to
```
[Error]:  Virtual type (dim, cof, etc.) cannot appear in this position
cooltt: encountered one or more errors
```
=> 📝 Use pp boxes in logging even if span is not available

test/import.cooltt
Just found a typo in `import.cooltt`.
=> 📝 Fix comments in import.cooltt

src/core/Refiner.ml, src/core/Refiner.mli, src/frontend/ConcreteSyntaxData.ml, src/frontend/Elaborator.ml, src/frontend/Grammar.mly, src/frontend/Tactics.ml, src/frontend/Tactics.mli, test/patch.cooltt, test/test.expected
Hello! I'm a first time cooltt contributor :)
This PR makes implicit the conversion between a signature indexed type family and its total space (as implemented in #280), and replaces `as` with `#` as the patch operator. Now instead of writing `fam # []`, one can write `fam` and `tp # [ patches ]` can be written if `tp` is either a signature indexed type family or a signature. This takes cooltt one step closer to the original total space conversion proposal in #267. 
A patch now looks like this:
```
def el : type := sig (A : type) (a : A)
def el-patch : type := el # [ A .= nat | a .= 4 ]
```
The definition of a category now looks like this:
```
def category : type :=
sig (ob : type)
(hom : sig (s : ob) (t : ob) → type)
(idn : (x : ob) -> hom # [ s .= x | t .= x ])
(seq : (f : hom) -> (g : …
```
=> 📥 Implicit Total Space Conversion

src/frontend/Tactics.ml, test/patch.cooltt, test/test.expected
The `intro_conversions` tactic (and the `total` tactic before it, actually) checked whether a certain term was equal to `Univ` or `ElStable Univ` by pattern matching, but did not reduce it first. So this test failed to type check:
```
def U : type := type
def test-unfold-total (fam : sig (x : nat) -> U) : U := fam
```
This PR fixes that.
=> 🩹 Unfold when pattern matching against Univ/El Univ in intro_conversions

src/core/Domain.ml, src/core/Syntax.ml, src/cubical/Cof.ml, src/cubical/Cof.mli
When checking how cofibrations are used across the codebase, I noticed that `dump` has been re-implemented many times, and that does not seem to be good.
=> 🗑 Use the blessed dumper for cofibrations

src/frontend/Elaborator.ml, src/frontend/Elaborator.mli, src/frontend/Tactics.ml, src/frontend/Tactics.mli, test/cool-total-space.cooltt, test/patch.cooltt, test/test.expected
This PR implements the proposal roughly described in #348 to make total spaces totally (lol) implicit whenever possible. We can now write down the definition of the category of types like this:
```
def types : category :=
struct (ob : type)
(hom : args => {args.s} -> {args.t})
(idn : x z => z)
(seq : f g x => g {f x})
(seqL : f i => f)
(seqR : f i => f)
(seqA : f g h i x => h {g {f x}})
```
(Closes #348)
* Total spaces where all fields but `fib` have been patched are handled by `intro_implicit_connectives`. The user need only write down the value of the `fib` field
* Total spaces with unpatched fields are still just regular signature types, and the user must write down a record to inhabit them
* Any term that synths to a total space will have it's `fib` field implicitly projected, …
=> 📥 Make Total Spaces Really Cool 😎

emacs/cooltt.el, src/core/CodeUnit.ml, src/core/CodeUnit.mli, src/core/CofBuilder.ml, src/core/CofThy.ml, src/core/CofVar.ml, src/core/CofVar.mli, src/core/Dim.ml, src/core/Dim.mli, src/core/Domain.ml, src/core/DomainData.ml, src/core/Quote.ml, src/core/Semantics.ml, src/core/Serialize.ml, src/core/Syntax.ml, src/frontend/Driver.ml, test/axiom.cooltt, test/test.expected
This PR brings back axioms/globals for virtual types, which were removed during the implementation of imports (see #190).
This was pretty mechanical luckily, and wasn't too difficult.
=> 🧟 0️⃣ 1️⃣ Resurrect Virtual Type Globals/Axioms

src/core/Syntax.ml
This PR fixes a bug in `Syntax.pp_sign`, where field labels were not bound during pretty printing, leading to this code
```
def bad : type := sig (A : type) (a : A) (b : A)
def test (x : bad) : type :=
let y := x in
?
```
causing this error
```
test.cooltt:5.2-5.3 [Info]:            
Emitted hole:
x : bad
y : sub {sig (A : type) (a : x) 
(y : cooltt: internal error, uncaught exception:
Failure("Pp printer: tried to resolve bound variable out of range")
```
=> 🩹 Bind field labels when pretty printing signatures

src/basis/Pp.ml, src/basis/Pp.mli, src/core/Quote.ml, src/core/Syntax.ml, src/frontend/Elaborator.ml, src/frontend/Tactics.ml, test/circle.cooltt, test/com.cooltt, test/elab.cooltt, test/groupoid-laws.cooltt, test/hcom-type.cooltt, test/hlevel.cooltt, test/isos.cooltt, test/nat-path.cooltt, test/path-types.cooltt, test/prelude.cooltt, test/test.expected, test/v.cooltt
~~(emoji needed)~~
This PR makes functions out of cofibration proofs implicit. So to inhabit `[ϕ] -> A` we can simply write down an element of `A` and it will be elaborated to a function. Similarly, if we have `f :  [ϕ] -> A`, it will be elaborated to `f *`. 
The main thing this is lacking is nice printing. We still print( functions out of) and (applications to) cofibration proofs, because we do not have types when printing. Not printing applications to `*` is straightforward, but conditionally not printing lambdas is more difficult. We may need to add separate core terms for these constructs.
Regardless of printing, I think having these proofs clutter only the core is superior to having them clutter both the surface language and the core.
=> 🙈 Implicit Cofibration Proofs

src/core/Quote.ml, src/core/Semantics.ml, src/core/Semantics.mli, test/test.expected
This PR updates the behavior of quoting on cofibration splits, now if `φ` is true, `[ φ => e ]` is quoted as `e`. This simplifies the display of some terms and boundary conditions. For instance, with this change, a boundary that was previously displayed as
```
Boundary:
j = 0 ∨ j = 1 ∨ i = 0 ∨ i = 1
|- i = 0 => sq 0 0
i = 1 => sq 0 0
⊤ => sq 0 0
⊤ => sq 0 0
⊤ => sq 0 0
⊤ => sq 0 0
⊤ => sq 0 0
i = 0 => sq 0 1
i = 1 => sq 0 1
⊤ => sq 0 1
⊤ => sq 0 1
⊤ => sq 0 1
⊤ => sq 0 1
⊤ => sq 0 1
i = 0 => sq 0 j
i = 1 => sq 0 j
```
becomes
```
Boundary:
j = 0 ∨ j = 1 ∨ i = 0 ∨ i = 1
|- j = 0 => sq 0 0
j = 1 => sq 0 1
i = 0 => sq 0 j
i = 1 => sq 0 j
```
=> 🙅 Delete true cofibration splits when quoting

.gitignore, README.md, cooltt.opam, flake.lock, flake.nix
This adds building with the Nix package manager as an option, which serves as a decent "just run this and it should work" option for those who don't want to bother to set up OPAM entirely, or for those who just want to *use* cooltt rather than *hack* on it.
This may be blocked on some issues in https://github.com/tweag/opam-nix:
- https://github.com/tweag/opam-nix/issues/12
- https://github.com/tweag/opam-nix/issues/13
However, it may be okay that the constraints on `bantorra`'s version are removed --- I'm not entirely sure about the implications of doing this, because I don't know your all's OPAM workflow.
=> ❄️ Add building with Nix as an option

.envrc, .gitignore, README.md, cooltt.opam, flake.lock, flake.nix
Rewrites flake.nix and pins some libraries to get the nix shell environment and nix builds working.
~Note that I had to pin `Kado` prior to `17206ca3d01fada34e34e60e1995b03609292b61` which has a breaking change.~
=> Fixes flake.nix
